In [1]:
import numpy as np

In [3]:
matrix=np.array([[1,2],[3,4]])
print (f'{matrix}')

[[1 2]
 [3 4]]


In [4]:
matrix=np.array([[1,2,3],[3,4,5],[6,7,8]])
print (f'{matrix}')

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [6]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=A+B
print(C)

[[ 6  8]
 [10 12]]


In [7]:
D=B-A
print(D)

[[4 4]
 [4 4]]


In [8]:
E=C-B
print(E)

[[1 2]
 [3 4]]


In [9]:
S1=np.array([[4,2],[6,8]])
S2=np.array([[2,2],[3,4]])
S=S1//S2
print(S)

[[2 1]
 [2 2]]


In [10]:
S3=S1.dot(S2)
print(S3)

[[14 16]
 [36 44]]


In [11]:
F= A.dot(B)
print(F)

[[19 22]
 [43 50]]


In [13]:
#transpose of the matrix
T=np.transpose(A)
print(T)

[[1 3]
 [2 4]]


In [14]:
T2=np.transpose(F)
print(T2)

[[19 43]
 [22 50]]


In [16]:
Fdet=np.linalg.det(F)
print(Fdet)

4.000000000000017


In [15]:
#how to get inverse of the matrix
Finverse=np.linalg.inv(F)
print(Finverse)

[[ 12.5   -5.5 ]
 [-10.75   4.75]]
